linters:
  disable-all: true
  presets:
    - bugs
    - error
    - format
    - style
    - metalinter
    - comment
    - complexity
    - performance
    - sql
    - test
    - unused
    # Disable these because of the various "guard" things, which are painful.
    # - import
    # - module
