linters:
  disable-all: true
  presets:
    - bugs
    #- comment
    #- complexity
    - error
    - format
    # Disable import because of the various "guard" things, which are painful.
    # - import
    - metalinter
    #- module
    #- performance
    #- sql
    #- style
    #- test
    #- unused
