name: gobbi go tests

on:
- push
- pull_request
- workflow_dispach

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Test
      run: go test -v ./...
